### ISSUE TITLE
"Your Google Cloud permissions are not enabled, so I cannot access the pre-trained models and datasets."

### ISSUE THREAD

**Issue by PanGao-1** [Jumponthemoon/WeatherDG#2]
您的谷歌云的权限没开，我们访问不了预训练模型和数据集。请设置一下权限，或更新一下链接。

**Comment by Jumponthemoon** [comment]
Just granted the access and I believe it would work now. Please let me know if you still have trouble in that.

**Comment by PanGao-1** [comment]
@Jumponthemoon The issue has been resolved. Thank you for your help !!

**Comment by JasonBourne1998** [comment]
> Just granted the access and I believe it would work now. Please let me know if you still have trouble in that.

Hi, could you please grant the access for me? Thanks!

**Comment by Jumponthemoon** [comment]
> > Just granted the access and I believe it would work now. Please let me know if you still have trouble in that.
> 
> Hi, could you please grant the access for me? Thanks!

Done.

**Comment by JasonBourne1998** [comment]
> > > Just granted the access and I believe it would work now. Please let me know if you still have trouble in that.
> > 
> > 
> > Hi, could you please grant the access for me? Thanks!
> 
> Done.

Thanks so much for the help! Seems that there is no diffusion model's training/fine-tuning code in the github, could you please provide the code ? Thanks!

**Comment by Jumponthemoon** [comment]
> > > > Just granted the access and I believe it would work now. Please let me know if you still have trouble in that.
> > > 
> > > 
> > > Hi, could you please grant the access for me? Thanks!
> > 
> > 
> > Done.
> 
> Thanks so much for the help! Seems that there is no diffusion model's training/fine-tuning code in the github, could you please provide the code ? Thanks!

Hi, the finetuning code hasn't been cleaned up yet but will be updated in the future.
